language: python
python:
  - "2.6"
  - "2.7"
services:
  - mongodb
install:
  - pip install .
  - pip install pep8
  - pip install pyflakes
script:
  - python setup.py test
  - pep8 --config=.pep8rc mtop
  - pyflakes mtop
